schema_version: 2
network: mainnet
contract_slug: mkpl
script_type: mkpl
old_script_type: marketplace_contract
deployment_handle_slug: mkpl
build:
  target: validators/mkpl.ak
  kind: validator
  parameters:
    marketplace_address: addr1xysgj7dndz9ql57jsh5y0ss258d0yl8wqfj4hy00ulyw6ueq39umx6y2plfa9p0gglpq4gw67f7wuqn9twg7le7ga4es4uake8
    authorizers:
      - "4da965a049dfd15ed1ee19fba6e2974a0b79fc416dd1796a1f97f5e1"
subhandle_strategy:
  namespace: handlecontract
  format: contract_slug_ordinal
assigned_handles:
  settings: []
  scripts:
    - marketplace@handle_scripts
ignored_settings: []
settings:
  type: marketplace_settings
  values:
    marketplace_address: addr1xysgj7dndz9ql57jsh5y0ss258d0yl8wqfj4hy00ulyw6ueq39umx6y2plfa9p0gglpq4gw67f7wuqn9twg7le7ga4es4uake8
    authorizers:
      - "4da965a049dfd15ed1ee19fba6e2974a0b79fc416dd1796a1f97f5e1"
